CREATE TABLE IF NOT EXISTS news (
    id VARCHAR(64) PRIMARY KEY,
    title VARCHAR(500) NOT NULL DEFAULT '',
    description TEXT NOT NULL,
    date VARCHAR(64) NOT NULL DEFAULT '',
    image VARCHAR(1000) NOT NULL DEFAULT '',
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ministries (
    id VARCHAR(64) PRIMARY KEY,
    title VARCHAR(500) NOT NULL DEFAULT '',
    description TEXT NOT NULL,
    schedule VARCHAR(500) NOT NULL DEFAULT '',
    leader VARCHAR(500) NOT NULL DEFAULT '',
    image VARCHAR(1000) NOT NULL DEFAULT '',
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS schedule_events (
    id VARCHAR(64) PRIMARY KEY,
    day VARCHAR(32) NOT NULL,
    time VARCHAR(32) NOT NULL DEFAULT '',
    title VARCHAR(500) NOT NULL DEFAULT '',
    sort_order INT NOT NULL DEFAULT 0,
    INDEX idx_day (day)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
